name: 'Thoughts beyond life '
favicon: null
layout_spectrum: 0.89566
typography_spectrum: 0.64691
title: 'Things that make you who you want to be starts with You ****'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b3fe'
    - '#f1ffff'
    - '#005df6'
    - '#a30000'
    - '#5d8200'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.827214244287461
  rhythmicContrast: 0.5
purpose: []
